name: API docs

on:
  push:
    tags: ['[0-9]+.[0-9]+*']

permissions:
  contents: write

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: code
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Sphinx and dependencies
        run: pip install sphinx requests==2.* requests-toolbelt==0.* appengine-python-standard
      - name: Build API docs
        run: sphinx-build . docs
        working-directory: code
      - name: Checkout pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
      - name: Deploy pages
        run: |
          SDK_VERSION_FOLDER=`echo "$SDK_VERSION" | awk --field-separator '.' '{print $1".x";}'`

          # Create .nojekyll if it doesn't exist yet
          touch .nojekyll

          mkdir -p "$SDK_VERSION_FOLDER"
          rsync --quiet --archive --checksum --delete --exclude .git ../code/docs/ "$SDK_VERSION_FOLDER/"
          # Remove .buildinfo and .doctrees generated by Sphinx
          if [ -f "$SDK_VERSION_FOLDER/.buildinfo" ]; then rm "$SDK_VERSION_FOLDER/.buildinfo"; fi
          if [ -d "$SDK_VERSION_FOLDER/.doctrees" ]; then rm -r "$SDK_VERSION_FOLDER/.doctrees"; fi
          if [ -e latest ]; then rm -r latest; fi
          ln -s "$SDK_VERSION_FOLDER" latest

          git config user.email "$USER_EMAIL"
          git config user.name "$USER_NAME"
          git add --all .
          # Only commit when there are changes
          git diff --quiet && git diff --staged --quiet || git commit --message "Generated API docs for version ${SDK_VERSION}"
          git push
        shell: bash
        working-directory: pages
        env:
          SDK_VERSION: ${{ github.ref_name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
          USER_NAME: ${{ github.event.pusher.name }}
