name: Deploy

on:
  push:
    tags: ['[0-9]+.[0-9]+*']

env:
  SDK_VERSION: ${{ github.ref_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Twine and dependencies
        run: pip install twine requests==2.* requests-toolbelt==0.* appengine-python-standard
      - name: Build
        run: python setup.py sdist --formats zip --dist-dir .
      - name: Verify
        run: twine check "connect-sdk-python3-${SDK_VERSION}.zip"
      - name: Deploy
        run: twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" "connect-sdk-python3-${SDK_VERSION}.zip"
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
